/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ready
         * @description Readiness probe (no external deps yet).
         */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/solve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Solve Endpoint
         * @description Optimize a meal plan (selections only; TypeScript computes the canonical proof).
         */
        post: operations["solve_endpoint_solve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CandidateFood */
        CandidateFood: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Meal Roles
             * @description meal roles this food may appear in
             */
            meal_roles: string[];
            /**
             * Per100G
             * @description nutrient key -> per-100g value; null == missing
             */
            per100g?: {
                [key: string]: number | null;
            };
            /** Tags */
            tags?: string[];
            /** Category */
            category?: string | null;
            /**
             * Is Pantry
             * @default false
             */
            is_pantry: boolean;
            /** Pantry Grams */
            pantry_grams?: number | null;
            /**
             * Min Grams
             * @default 0
             */
            min_grams: number;
            /**
             * Max Grams
             * @default 300
             */
            max_grams: number;
        };
        /** ConstraintViolation */
        ConstraintViolation: {
            /** Key */
            key: string;
            /** Kind */
            kind: string;
            /** Needed */
            needed?: number | null;
            /** Achieved */
            achieved?: number | null;
            /** Suggestion */
            suggestion: string;
        };
        /** Diagnostics */
        Diagnostics: {
            /** Candidate Count */
            candidate_count: number;
            /** Selected Count */
            selected_count: number;
            /** Binding Constraints */
            binding_constraints?: string[];
            /** Notes */
            notes?: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Status */
            status: string;
            /** Service */
            service: string;
            /** Version */
            version: string;
        };
        /** Infeasibility */
        Infeasibility: {
            /** Explanation */
            explanation: string;
            /** Violations */
            violations?: components["schemas"]["ConstraintViolation"][];
        };
        /** LockedIngredient */
        LockedIngredient: {
            /** Food Id */
            food_id: string;
            /** Meal Role */
            meal_role: string;
            /** Grams */
            grams: number;
        };
        /** MealResult */
        MealResult: {
            /** Role */
            role: string;
            /** Items */
            items?: components["schemas"]["SelectedItem"][];
        };
        /** MealSpec */
        MealSpec: {
            /** Role */
            role: string;
            /**
             * Required
             * @default true
             */
            required: boolean;
            /**
             * Template Tags
             * @description each tag must be covered by >=1 selected food
             */
            template_tags?: string[];
            /** Max Total Grams */
            max_total_grams?: number | null;
        };
        /** NutrientConstraint */
        NutrientConstraint: {
            /** Key */
            key: string;
            mode: components["schemas"]["NutrientMode"];
            /** Min */
            min?: number | null;
            /** Target */
            target?: number | null;
            /** Max */
            max?: number | null;
            /**
             * Tolerance Low Pct
             * @default 10
             */
            tolerance_low_pct: number;
            /**
             * Tolerance High Pct
             * @default 10
             */
            tolerance_high_pct: number;
        };
        /**
         * NutrientMode
         * @enum {string}
         */
        NutrientMode: "DISABLED" | "MINIMUM" | "TARGET" | "MAXIMUM";
        /** ObjectiveWeights */
        ObjectiveWeights: {
            /**
             * Pantry
             * @default 100
             */
            pantry: number;
            /**
             * Food Count
             * @default 10
             */
            food_count: number;
            /**
             * Deviation
             * @default 1
             */
            deviation: number;
        };
        /** SelectedItem */
        SelectedItem: {
            /** Food Id */
            food_id: string;
            /** Name */
            name: string;
            /** Grams */
            grams: number;
            /**
             * From Pantry
             * @default false
             */
            from_pantry: boolean;
        };
        /**
         * SolveMode
         * @enum {string}
         */
        SolveMode: "strict" | "diagnostic";
        /** SolveRequest */
        SolveRequest: {
            /** Foods */
            foods: components["schemas"]["CandidateFood"][];
            /** Meals */
            meals: components["schemas"]["MealSpec"][];
            /** Nutrient Constraints */
            nutrient_constraints?: components["schemas"]["NutrientConstraint"][];
            /** Banned Food Ids */
            banned_food_ids?: string[];
            /** Locked Ingredients */
            locked_ingredients?: components["schemas"]["LockedIngredient"][];
            /**
             * Gram Increment
             * @default 5
             */
            gram_increment: number;
            /**
             * Seed
             * @default 0
             */
            seed: number;
            /**
             * Time Budget Sec
             * @default 5
             */
            time_budget_sec: number;
            /** @default strict */
            mode: components["schemas"]["SolveMode"];
            weights?: components["schemas"]["ObjectiveWeights"];
        };
        /** SolveResponse */
        SolveResponse: {
            status: components["schemas"]["SolveStatus"];
            /** Feasible */
            feasible: boolean;
            /** Meals */
            meals?: components["schemas"]["MealResult"][];
            /** Nutrient Totals */
            nutrient_totals?: {
                [key: string]: number;
            };
            /** Objective Score */
            objective_score?: number | null;
            /**
             * Solve Time Ms
             * @default 0
             */
            solve_time_ms: number;
            /**
             * Seed
             * @default 0
             */
            seed: number;
            diagnostics: components["schemas"]["Diagnostics"];
            infeasibility?: components["schemas"]["Infeasibility"] | null;
        };
        /**
         * SolveStatus
         * @enum {string}
         */
        SolveStatus: "OPTIMAL" | "FEASIBLE" | "INFEASIBLE" | "TIME_LIMIT" | "ERROR";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    solve_endpoint_solve_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SolveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SolveResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
